Repository DawnbrandBots/emcee-tournament-bot, pull requests merged in 2020-07, with the labels that each got.

#34 Fix severe bugs when confirming and dropping participants
  src/actions/index.ts
  src/commands/tournament.ts
  src/discordDeck.ts
  src/models/index.ts
  src/tournament.ts
Labels: bug

#36 Two package metadata updates
  package-lock.json
  package.json
Labels: dependencies

#37 Docker: fix up for deploy
  Dockerfile
  docker-compose.yaml
Labels: enhancement

#39 Add feature to synchronise tournament DB with challonge remote
  package-lock.json
  src/actions/index.ts
  src/challonge.ts
  src/commands/index.ts
  src/commands/score.ts
  src/commands/tournament.ts
  src/tournament.ts
Labels: enhancement
