Repository DawnbrandBots/emcee-tournament-bot, pull requests merged in 2021-02, with the labels that each got.

#150 Update `forcescore` command to be able to change closed matches
  src/TournamentManager.ts
  src/commands/forcescore.ts
  src/website/challonge.ts
  src/website/interface.ts
  test/commandHandler.ts
  test/mocks/tournament.ts
  test/mocks/website.ts
  test/tournamentManager.ts
  test/website.ts
Labels: bug

#168 Amend score to tie if both players drop from a match
  src/TournamentManager.ts
Labels: enhancement

#181 Create changelog.md
  changelog.md
Labels: documentation

#192 Extract simple commands from TournamentManager
  src/TournamentManager.ts
  src/commands/addbye.ts
  src/commands/addchannel.ts
  src/commands/addhost.ts
  src/commands/cancel.ts
  src/commands/deck.ts
  src/commands/drop.ts
  src/commands/dump.ts
  src/commands/finish.ts
  src/commands/forcedrop.ts
  src/commands/list.ts
  src/commands/open.ts
  src/commands/pie.ts
  src/commands/players.ts
  src/commands/removebye.ts
  src/commands/removechannel.ts
  src/commands/removehost.ts
  src/commands/round.ts
  src/commands/start.ts
  src/commands/sync.ts
  src/commands/update.ts
  src/database/postgres.ts
  test/commands/addbye.unit.ts
  test/commands/addchannel.unit.ts
  test/commands/common.ts
  test/commands/drop.unit.ts
  test/commands/dump.unit.ts
  test/commands/finish.unit.ts
  test/commands/list.unit.ts
  test/commands/pie.unit.ts
  test/commands/players.unit.ts
  test/commands/removebye.unit.ts
  test/commands/update.unit.ts
  test/mocks/database.ts
  test/tournamentManager.ts
Labels: enhancement

#194 Create DeckManager class for CommandSupport
  src/Command.ts
  src/TournamentManager.ts
  src/commands/deck.ts
  src/commands/dump.ts
  src/commands/pie.ts
  src/commands/players.ts
  src/deck.ts
  src/deck/deck.ts
  src/deck/discordDeck.ts
  src/discord/interface.ts
  src/index.ts
  test/Command.unit.ts
  test/commands/common.ts
  test/commands/deck.unit.ts
  test/commands/dump.unit.ts
  test/commands/pie.unit.ts
  test/commands/players.unit.ts
  test/deck.ts
  test/discord.ts
  test/mocks/tournament.ts
  test/tournamentManager.ts
Labels: enhancement

#195 Copy permissions and old changelog
  .github/workflows/docker.yml
  README.md
  changelog.md
Labels: documentation
