Repository DawnbrandBots/emcee-tournament-bot, pull requests merged in 2021-01, with the labels that each got.

#95 Add guides for host commands
  Dockerfile
  guides/create.template.md
  guides/open.template.md
  guides/player.template.md
  guides/start.template.md
  src/TournamentManager.ts
  src/commands/create.ts
  src/index.ts
  test/commandHandler.ts
  test/commands/create.unit.ts
  test/mocks/tournament.ts
  test/tournamentManager.ts
Labels: enhancement

#94 Send Direct Messages to players about their opponent on a new round
  src/TournamentManager.ts
  src/commands/round.ts
  src/website/interface.ts
Labels: enhancement

#97 Handle failure to send matchup DM
  src/TournamentManager.ts
  src/database/postgres.ts
  src/discord/eris.ts
  src/discord/interface.ts
  test/mocks/discord.ts
Labels: bug

#102 Fix algorithm for assigning byes to players
  src/TournamentManager.ts
  src/website/interface.ts
  test/website.ts
Labels: bug

#106 Fix algorithm for assigning byes to players
  src/TournamentManager.ts
  src/website/interface.ts
  test/website.ts
Labels: bug

#110 Properly handle deck submission without attached deck
  src/TournamentManager.ts
  src/deck/discordDeck.ts
  src/util/errors.ts
  test/deck.ts
Labels: bug

#109 Fix check for challonge URL being taken
  src/TournamentManager.ts
Labels: bug

#108 Fix website#getBye
  src/website/interface.ts
Labels: bug

#135 Do not send reaction error messages to DMs
  src/TournamentManager.ts
  src/discord/eris.ts
Labels: bug, javascript

#140 Fix double entity remove resulting in SubjectWithoutIdentifierError
  src/timer.ts
Labels: bug

#136 Properly handle submitting score with a closed match
  src/TournamentManager.ts
  src/website/challonge.ts
  src/website/interface.ts
Labels: bug, javascript

#137 Tournament: Concede open match for dropping player
  guides/player.template.md
  src/TournamentManager.ts
  test/tournamentManager.ts
Labels: enhancement, javascript

#145 Fix challonge bye detection
  src/website/challonge.ts
  src/website/interface.ts
  test/mocks/website.ts
Labels: bug

#148 Challonge: Update getMatches behaviour
  src/website/challonge.ts
  src/website/interface.ts
  test/mocks/website.ts
  test/website.ts
Labels: enhancement

#149 Add round number back to new round message
  src/TournamentManager.ts
  test/mocks/website.ts
Labels: enhancement
